### PR TITLE
Add color in video track

### PR DESCRIPTION
**Pull request by chenchao1983**
This change added the Colour element under a video track entry.

### CODE REVIEW

**Comment by chenchao1983** [comment]
This change is aimed to enable the "Colour" element under Track->TrackEntry->Video element. Using this element, we can provide metadata about video colour space using matroska. This will help YouTube to use Matroska for muxing HDR/wide-colour-gamut videos.

The Colour element is proposed by Google Inc. to IETF and will be supported in Matroska version 5.

**Comment by chenchao1983** [comment]
Please refer to this [email thread](https://mailarchive.ietf.org/arch/search/?email_list=cellar) for more details of the proposal.

**Comment by mbunkus** [comment]
Thanks for the pull request, but this is not how new classes are added to libmatroska. The classes for all the elements is generated automatically by the tools in the [spectool part](https://github.com/Matroska-Org/foundation-source/tree/master/spectool) of the [foundation-source repository](https://github.com/Matroska-Org/foundation-source/). To be more precise: the source is the XML file [specdata.xml](https://github.com/Matroska-Org/foundation-source/blob/master/spectool/specdata.xml).

Please create a pull request against that file. We'll take care of updating libmatroska afterwards. Thanks.

**Comment by chenchao1983** [comment]
Thank you very much for the information. I will make changes to the foundation-source repository.

**Pull request closed without merging**
