### PR TITLE
use assignment by reference instead of pointers

### PR DESCRIPTION
**Pull request by robUx4**
No need to dereference a pointer.

### CODE REVIEW

**Review by mbunkus — CHANGES_REQUESTED** [review]
While I agree that you can just cast the reference, you don't need to cast for the vast majority of these cases in the first place. Just use `elt.SetValue(…)` for all those places where the only use is to assign values. The casts are only there from way back when the `SetValue()` & `GetValue()` functions didn't exist.

**Comment by robUx4** [comment]
Ah, I thought the operator was the preferred way. I had some troubles with it and ending up removing the factorization of those for now. If you think it's better not to have them at all, I can remove them for good.

**Comment by mbunkus** [comment]
We can leave the existing `operator <whatever>()` in the classes for compatibility purposes, but we should not really use them inside the library anymore. I'd even be fine with removing them altogether, even the member functions themselves.

**Comment by robUx4** [comment]
Closing in favor of #136

**Pull request closed without merging**
