### PR TITLE
[RFC] keep the min/max/webm/divx information for each element

### PR DESCRIPTION
**Pull request by robUx4**
Based on https://github.com/Matroska-Org/libebml/pull/207

For now it's only informational but it can be used later for a libmatroska-based mkvalidator/mkclean. The way it's handled may evolve given how I manage to recode these tools.

### CODE REVIEW

**Comment by mbunkus** [comment]
This branch doesn't merge with the current `master` at the moment. This prevents me from reviewing the corresponding libEBML PRs (Matroska-Org/libebml#207, Matroska-Org/libebml#211). Can you please rebase it  (or probably regenerate `KaxSemantic.cpp`, probably faster)? Thanks.

**Comment by robUx4** [comment]
I rebased this branch, the libmatroska one and the spectools one.

**Review by mbunkus — APPROVED** [review]

**Comment by mbunkus** [comment]
I _did_ merge & push the branch… not sure why Github thinks I didn't?

**Comment by robUx4** [comment]
Indeed, that's weird but the code seems to be OK.

**Pull request closed without merging**
