### PR TITLE
CI: add a basic compilation test

### PR DESCRIPTION
**Pull request by robUx4**
It neeeds to build libebml first.

### CODE REVIEW

**Comment by robUx4** [comment]
@mbunkus any idea what the [IMPORTED_LOCATION](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_LOCATION.html) problem is with Ubuntu/macOS targets ? The build works fine with MSVC.

IMO we can merge this even if it fails on some targets. At least we have one compilation check.

**Comment by robUx4** [comment]
```
cmake --build libebml/_build
cmake --install libebml/_build --prefix ${GITHUB_WORKSPACE}/_built
```

Looks like with MSVC the former build a Debug configuration and the latter a Release configuration 🤦

**Comment by mbunkus** [comment]
No idea, sorry. What I use on Linux is basically:

```
cd libebml
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/ebmlmatroska -DBUILD_SHARED_LIBS=no ..
make
make install
cd ../../libmatroska
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/ebmlmatroska -DBUILD_SHARED_LIBS=no ..
make
make install
```

**Comment by robUx4** [comment]
In the end I found a working solution. It seems forcing the (Debug or Release) configuration in Linux makes it not working. And not forcing it on Windows targets has its own issues. So I just split everything.

**Pull request merged**
