### PR TITLE
import the Signed VINT code from libebml and clean it up

### PR DESCRIPTION
**Pull request by robUx4**
Once this is merged, https://github.com/Matroska-Org/libebml/issues/145 can be done.

### CODE REVIEW

**Review by mbunkus — APPROVED** [review]
LGTM, and passes the MKVToolNix test suite (together with the current libEBML master).

I guess you plan to remove the obsolete functions from libEBML, too?

**Comment by mbunkus** [comment]
Ah right, there's an issue for that already. Was just looking at the PRs.

**Comment by robUx4** [comment]
Not sure it will be removed. I can be marked as deprecated, in case some people are actually using the code.

**Comment by mbunkus** [comment]
MKVToolNix isn't using any of the three functions; I've checked before commenting here.

**Pull request merged**
