### PR TITLE
use push_back

### PR DESCRIPTION
**Pull request by neheb**
This is a vector. No need for iterators.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by robUx4** [comment]
Isn't there a way to make an exact copy of an `std::vector` in just one call ?

**Comment by mbunkus** [comment]
As you need to modify each element, it isn't a trivial call, but you could probably just use `std::transform`, e.g. something like this (untested):

```c++
  std::transform(ElementToClone.begin(), ElementToClone.end(), std::back_inserter(myBuffers),
                 [](auto elt) { return elt->Clone(); });
```

Whether or not that is easier to read is up to the user, I guess. This type of `std::transform()` call is pretty standard, though; it's one of the [canonical examples](https://en.cppreference.com/w/cpp/algorithm/transform) over on cppreference.

**Comment by mbunkus** [comment]
Thanks.

**Comment by neheb** [comment]
I'd avoid std::transform. I've seen it behave wrong before for unexplained reasons. It uses push_back internally anyway.

**Pull request merged**
